### ISSUE TITLE
Errors on installing on Windows 10

### ISSUE THREAD

**Issue by chrisaww** [mi-g/joclyboard#1] opened 2017-05-09 17:02 UTC
Tried a default install with git clone https://github.com/mi-g/joclyboard.git.
The console displayed the following
npm WARN package.json JoclyBoard@0.9.5 license should be a valid SPDX license expression
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update t
o graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN optional dep failed, continuing 7zip-bin-mac@1.0.1
npm WARN optional dep failed, continuing 7zip-bin-linux@1.0.3
\
> electron@1.6.6 postinstall C:\Users\CAWW\joclyboard\node_modules\electron
> node install.js

C:\Users\CAWW\joclyboard\node_modules\electron\install.js:47
  throw err
  ^

Error: getaddrinfo ENOTFOUND github.com github.com:443
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
 npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! electron@1.6.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.6 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

The last lines of debug log are
66329 error Windows_NT 10.0.14393
66330 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
66331 error node v4.5.0
66332 error npm  v2.15.9
66333 error code ELIFECYCLE
66334 error electron@1.6.6 postinstall: `node install.js`
66334 error Exit status 1
66335 error Failed at the electron@1.6.6 postinstall script 'node install.js'.
66335 error This is most likely a problem with the electron package,
66335 error not with npm itself.
66335 error Tell the author that this fails on your system:
66335 error     node install.js
66335 error You can get information on how to open an issue for this project with:
66335 error     npm bugs electron
66335 error Or if that isn't available, you can get their info via:
66335 error
66335 error     npm owner ls electron
66335 error There is likely additional logging output above.
66336 verbose exit [ 1, true ]
66337 verbose unbuild node_modules\electron
66338 info preuninstall electron@1.6.6
66339 info uninstall electron@1.6.6
66340 verbose unbuild rmStuff electron@1.6.6 from C:\Users\CAWW\joclyboard\node_modules
66341 silly gentlyRm C:\Users\CAWW\joclyboard\node_modules\.bin\electron.cmd is being gently removed
66342 silly gentlyRm verifying C:\Users\CAWW\joclyboard is an npm working directory
66343 silly gentlyRm containing path C:\Users\CAWW\joclyboard is under npm's control, in C:\Users\CAWW\joclyboard
66344 silly gentlyRm deletion target C:\Users\CAWW\joclyboard\node_modules\.bin\electron.cmd is under C:\Users\CAWW\joclyboard
66345 verbose gentlyRm vacuuming from C:\Users\CAWW\joclyboard\node_modules\.bin\electron.cmd up to C:\Users\CAWW\joclyboard
66346 silly vacuum-fs removing C:\Users\CAWW\joclyboard\node_modules\.bin\electron.cmd
66347 silly vacuum-fs quitting because other entries in C:\Users\CAWW\joclyboard\node_modules\.bin
66348 silly gentlyRm C:\Users\CAWW\joclyboard\node_modules\.bin\electron is being gently removed
66349 silly gentlyRm verifying C:\Users\CAWW\joclyboard is an npm working directory
66350 silly gentlyRm containing path C:\Users\CAWW\joclyboard is under npm's control, in C:\Users\CAWW\joclyboard
66351 silly gentlyRm deletion target C:\Users\CAWW\joclyboard\node_modules\.bin\electron is under C:\Users\CAWW\joclyboard
66352 verbose gentlyRm vacuuming from C:\Users\CAWW\joclyboard\node_modules\.bin\electron up to C:\Users\CAWW\joclyboard
66353 silly vacuum-fs removing C:\Users\CAWW\joclyboard\node_modules\.bin\electron
66354 silly vacuum-fs quitting because other entries in C:\Users\CAWW\joclyboard\node_modules\.bin
66355 info postuninstall electron@1.6.6
66356 silly gentlyRm C:\Users\CAWW\joclyboard\node_modules\electron is being purged from base C:\Users\CAWW\joclyboard
66357 verbose gentlyRm don't care about contents; nuking C:\Users\CAWW\joclyboard\node_modules\electron
66358 silly vacuum-fs purging C:\Users\CAWW\joclyboard\node_modules\electron
66359 silly vacuum-fs quitting because other entries in C:\Users\CAWW\joclyboard\node_modules
regards

**Comment by mi-g** [comment] 2017-05-09 17:10
> Error: getaddrinfo ENOTFOUND github.com github.com:443

It looks like a network error. Can you check connectivity and try again ?

**Comment by chrisaww** [comment] 2017-05-09 17:43
Thanks for the prompt response and for being patient with a novice.
Still getting the same error though on second attempt.
I do not usually have network errors

 electron@1.6.6 postinstall C:\Users\CAWW\joclyboard\node_modules
 node install.js

:\Users\CAWW\joclyboard\node_modules\electron\install.js:47
 throw err
 ^

rror: getaddrinfo ENOTFOUND github.com github.com:443
   at errnoException (dns.js:27:10)
   at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
npm ERR! Windows_NT 10.0.14393
pm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program F
all"
pm ERR! node v4.5.0
pm ERR! npm  v2.15.9
pm ERR! code ELIFECYCLE

pm ERR! electron@1.6.6 postinstall: `node install.js`
pm ERR! Exit status 1
pm ERR!
pm ERR! Failed at the electron@1.6.6 postinstall script 'node ins
pm ERR! This is most likely a problem with the electron package,
pm ERR! not with npm itself.

**Comment by mi-g** [comment] 2017-05-09 17:50
what is the command you type exactly when get this error ?

**Comment by chrisaww** [comment] 2017-05-09 17:56
from within the joclyboard directory
npm install

**Comment by mi-g** [comment] 2017-05-09 20:07
I just tried again from Windows 10:
```
$ git clone https://github.com/mi-g/joclyboard.git
$ cd .\joclyboard\
$ npm install
```
and it worked ok.

Let's compare our `npm` and `node` versions:
```
$ npm -v
3.10.10
$ node -v
v6.10.2
```
What do you get ?

**Comment by chrisaww** [comment] 2017-05-09 21:59
Aha ha. could be this. npm -v
2.15.9
 node -vv4.5.0
After updating 
npm -v 
3.10.10node -vv6.10.3
Still having a problemconsole shows the following:
PS C:\Users\CAWW\joclyboard> 'npm install' - typed by me the rest is script generated

> electron@1.6.6 postinstall C:\Users\CAWW\joclyboard\node_modules\electron
> node install.js

C:\Users\CAWW\joclyboard\node_modules\electron\install.js:47
  throw err
  ^

Error: getaddrinfo ENOTFOUND github-cloud.s3.amazonaws.com github-cloud.s3.amazonaws.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules\electron-builder\node_modules\7zip-bin
\node_modules\7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":
"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@^1.0.3 (node_modules\electron-builder\node_modules\7zip-b
in\node_modules\7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.0.3: wanted {"os":"linux","arch"
:"any"} (current: {"os":"win32","arch":"x64"})
npm WARN JoclyBoard@0.9.5 license should be a valid SPDX license expression
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.6.6 postinstall: `node install.js`
npm ERR! Exit status 1

**Comment by chrisaww** [comment] 2017-05-09 22:06
I have just searched for electron errors and it seems I am not the first
Failed at the electron@1.4.13 postinstall script 'node install.js' · Issue #8339 · electron/electron
looks like I have to move forward line by line.I'll let you know if I succeed in due course.Thanks again for your input

  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
Failed at the electron@1.4.13 postinstall script 'node install.js' ...
 Electron version: 1.4.13 Operating system: Windows 10 64-bit Actual behavior 14409 error node v7.3.0 14410 err...  |   |

  |

  |

**Comment by mi-g** [comment] 2017-05-09 22:06
Could you remove the `node_modules` directory and do `npm install` again, so now that you run the correct version, it's better to start on a clean base.

**Comment by chrisaww** [comment] 2017-05-10 09:35
I even removed the joclyboard directory and resubmitted git clone ....One step forward on node install.js  I now get a tree listing under electron@1.6.6
and the script ends 
--------npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules\7zip-bin\node_modules\7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":
"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@^1.0.3 (node_modules\7zip-bin\node_modules\7zip-bin-linux
):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.0.3: wanted {"os":"linux","arch"
:"any"} (current: {"os":"win32","arch":"x64"})
npm WARN ajv-keywords@2.0.0 requires a peer of ajv@>=5.0.0 but none was installed.
npm WARN JoclyBoard@0.9.5 license should be a valid SPDX license expression----------------------------------------------------------However when entering  'npm run app-install' I get JoclyBoard@0.9.5 app-install C:\Users\CAWW\joclyboard
 cd app && npm install

pm ERR! Windows_NT 10.0.14393
pm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
all"
pm ERR! node v6.10.3
pm ERR! npm  v3.10.10
pm ERR! code ENOTFOUND
pm ERR! errno ENOTFOUND
pm ERR! syscall getaddrinfo

pm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
pm ERR! network This is most likely not a problem with npm itself
pm ERR! network and is related to network connectivity.
pm ERR! network In most cases you are behind a proxy or have bad network settings.
pm ERR! network
pm ERR! network If you are behind a proxy, please make sure that the
pm ERR! network 'proxy' config is set properly.  See: 'npm help config'

pm ERR! Please include the following file with any support request:
pm ERR!     C:\Users\CAWW\joclyboard\app\npm-debug.log

pm ERR! Windows_NT 10.0.14393
pm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run
 "app-install"
pm ERR! node v6.10.3
pm ERR! npm  v3.10.10
pm ERR! code ELIFECYCLE
pm ERR! JoclyBoard@0.9.5 app-install: `cd app && npm install`
pm ERR! Exit status 1
pm ERR!
pm ERR! Failed at the JoclyBoard@0.9.5 app-install script 'cd app && npm install'.
pm ERR! Make sure you have the latest version of node.js and npm installed.
pm ERR! If you do, this is most likely a problem with the JoclyBoard package,
pm ERR! not with npm itself.
pm ERR! Tell the author that this fails on your system:
pm ERR!     cd app && npm install
pm ERR! You can get information on how to open an issue for this project with:
pm ERR!     npm bugs JoclyBoard
pm ERR! Or if that isn't available, you can get their info via:
pm ERR!     npm owner ls JoclyBoard
pm ERR! There is likely additional logging output above.

pm ERR! Please include the following file with any support request:
pm ERR!     C:\Users\CAWW\joclyboard\npm-debug.log
again thanks for your patience

**Comment by mi-g** [comment] 2017-05-10 10:02
> npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443

The problem is definitely related to your network access.

Is there any chance you are using a proxy to access the web ?
[This link](http://stackoverflow.com/questions/23193614/npm-err-network-getaddrinfo-enotfound) may help fixing the issue.

**Comment by chrisaww** [comment] 2017-05-11 17:01
a) My home is  connected to an ISP with a 'broadband' connection.b) I have do have worries about Windows10 stability. I have rebooted several times and get different quality connections.c) I have re-run npm run app-install and it appears to run cleanly. 
Apart from the tree ouput the only script message of note wasnpm WARN JoclyBoard@0.9.5 license should be a valid SPDX license expression 
However on running npm start I get JoclyBoard@0.9.5 start C:\Users\CAWW\joclyboard
 node_modules/electron/cli.js app || true

node_modules' is not recognized as an internal or external command,
perable program or batch file.
true' is not recognized as an internal or external command,
perable program or batch file.

pm ERR! Windows_NT 10.0.14393
pm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\
t"
pm ERR! node v6.10.3
pm ERR! npm  v3.10.10
pm ERR! code ELIFECYCLE
pm ERR! JoclyBoard@0.9.5 start: `node_modules/electron/cli.js app || true`
pm ERR! Exit status 1
pm ERR!
pm ERR! Failed at the JoclyBoard@0.9.5 start script 'node_modules/electron/cli.js app || true'.
pm ERR! Make sure you have the latest version of node.js and npm installed.
Do I need to clean right  back to the beginning or can I just remove a sub-directory to get the install to rebuild correctly
regardsChris

**Comment by mi-g** [comment] 2017-05-11 17:18
Do we agree you follow the Windows instructions from [this page](https://github.com/mi-g/joclyboard/wiki/Installing-JoclyBoard-from-Github) and type `electron app` from the `JoclyBoard` directory to start the app ?

**Comment by chrisaww** [comment] 2017-05-12 14:58
Many thanks.All is working. Albeit connectivity timeouts meant serveral reinstalls before I got there. 
The games are impressive as is your patience.

**Comment by mi-g** [comment] 2017-05-12 15:14
:)

I am about to release a new version of JoclyBoard. Some bug fixes and great new features: snapshot taking and board video capture. Think of doing a `git pull origin master` in a few hours.

Since it's good for you now, i close this bug.

**Closed by mi-g** 2017-05-12 15:14 UTC
